CAPTION_TASK = "web_caption"
HEAD_OCR_TASK = "head_ocr"
WEBQA_TASK = "webqa"
ELEMENT_OCR_TASK = "element_ocr"
ACTION_PREDICTION_TASK = "action_prediction"
ELEMENT_GROUND_TASK = "element_ground"
ACTION_GROUND_TASK = "action_ground"
